language: node_js
node_js:
- "node"
cache:
  directories:
  - "node_modules" # This will tell Travis CI to cache the dependencies
script: npm test # Here you could also run the build step of your application
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
- provider: script # Run a custom deployment script which we will define below
  script: now --token $NOW_TOKEN --public
  skip_cleanup: true
  on:
    master: true
